CREATE TABLE PERFIL(
	ID UNIQUEIDENTIFIER PRIMARY KEY,
	NOME VARCHAR(25) NOT NULL UNIQUE);
GO

INSERT INTO PERFIL(ID, NOME)
	VALUES(NEWID(), 'Operador'),
	 (NEWID(), 'Administrador');
GO

CREATE TABLE USUARIO(
	ID UNIQUEIDENTIFIER PRIMARY KEY,
	NOME VARCHAR(150) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL UNIQUE,
	SENHA VARCHAR(100) NOT NULL,
	PERFILID UNIQUEIDENTIFIER NOT NULL,
	FOREIGN KEY(PERFILID)
	REFERENCES PERFIL(ID));
GO